version: "2.2"
services:
  sample-service:
    image: node:6.9.5-alpine
    command: node test.js
    networks:
      - gatling_network
    volumes:
      - ./sample-service/test.js:/test.js:ro
    ports:
      - "8000:8000"
  gatling-runner:
    image: gatling:2.3.0
    scale: 2 # Scale to see the result of multiple nodes
    build:
      context: gatling/2.3.0
    command: [-s, sample.SampleService]
    networks:
      - gatling_network
    depends_on:
      - grafana
    environment:
      - LOCAL_USER_ID=`id -u $USER`
    volumes:
      - ./gatling/2.3.0/simulations:/opt/app/java/gatling/user-files/simulations
      - ./gatling/2.3.0/results:/opt/app/java/gatling/results
  influxdb:
    image: influxdb:2.3.0
    build:
      context: influxdb/1.2.0-alpine
    networks:
      - gatling_network
    ports:
      - "8083:8083"
      - "8086:8086"
      - "2003:2003"
  grafana:
    image: grafana
    build:
      context: grafana
    networks:
      - gatling_network
    ports:
      - "3000:3000"
networks:
  gatling_network:
